import apple from "./img/mobile/Apple iphone 13.webp";
import samsung from "./img/mobile/Samsung Galaxy Note20.webp";
import xiaomi from "./img/mobile/Xiaomi Redmi Note 11 Pro Plus.webp";
import { v4 as uuidv4 } from "uuid";

export const MobileState = () => {
  return [
    {
      appleBrand: [
        {
          name: "iphone13",
          memory: "128GB",
          Img: apple,
          url: "/mobile/apple/13128",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "iphone13",
          memory: "256GB",
          Img: apple,
          url: "/mobile/apple/13256",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "iphone13",
          memory: "512GB",
          Img: apple,
          url: "/mobile/apple/13512",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "iphone13pro",
          memory: "128GB",
          Img: apple,
          url: "/mobile/apple/13pro128",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "iphone13pro",
          memory: "256GB",
          Img: apple,
          url: "/mobile/apple/13pro256",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "iphone13pro",
          memory: "512GB",
          Img: apple,
          url: "/mobile/apple/13pro512",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "iphone13promax",
          memory: "128GB",
          Img: apple,
          url: "/mobile/apple/13promax128",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "iphone13promax",
          memory: "256GB",
          Img: apple,
          url: "/mobile/apple/13promax256",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "iphone13promax",
          memory: "512GB",
          Img: apple,
          url: "/mobile/apple/13promax512",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
      ],
    },
    {
      samsungBrand: [
        {
          name: "Samsung Note20",
          memory: "128GB",
          Img: samsung,
          url: "/mobile/samsung/note20128",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Samsung Note20",
          memory: "256GB",
          Img: samsung,
          url: "/mobile/samsung/note20256",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Samsung Note20",
          memory: "512GB",
          Img: samsung,
          url: "/mobile/samsung/note20512",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Samsung S20",
          memory: "128GB",
          Img: samsung,
          url: "/mobile/samsung/s20128",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Samsung S20",
          memory: "256GB",
          Img: samsung,
          url: "/mobile/samsung/s20256",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Samsung S20",
          memory: "512GB",
          Img: samsung,
          url: "/mobile/samsung/s20512",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Samsung Note20 Ultra",
          memory: "128GB",
          Img: samsung,
          url: "/mobile/samsung/note20u128",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Samsung Note20 Ultra",
          memory: "256GB",
          Img: samsung,
          url: "/mobile/samsung/note20u256",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Samsung Note20 Ultra",
          memory: "512GB",
          Img: samsung,
          url: "/mobile/samsung/note20u512",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
      ],
    },
    {
      xiaomiBeand: [
        {
          name: "Xiaomi Redmi Note 11 Pro Plus",
          memory: "128GB",
          Img: xiaomi,
          url: "/mobile/xiaomi/11proplus",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Xiaomi Redmi Note 11 Pro Plus",
          memory: "256GB",
          Img: xiaomi,
          url: "/mobile/xiaomi/11proplus",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Xiaomi Redmi Note 11 Pro Plus",
          memory: "512GB",
          Img: xiaomi,
          url: "/mobile/xiaomi/11proplus",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Xiaomi Redmi Note 11 Pro",
          memory: "128GB",
          Img: xiaomi,
          url: "/mobile/xiaomi/11proplus",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Xiaomi Redmi Note 11 Pro",
          memory: "256GB",
          Img: xiaomi,
          url: "/mobile/xiaomi/11proplus",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Xiaomi Redmi Note 11 Pro",
          memory: "512GB",
          Img: xiaomi,
          url: "/mobile/xiaomi/11proplus",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Xiaomi Redmi Note 11",
          memory: "128GB",
          Img: xiaomi,
          url: "/mobile/xiaomi/11proplus",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Xiaomi Redmi Note 11",
          memory: "256GB",
          Img: xiaomi,
          url: "/mobile/xiaomi/11proplus",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
        {
          name: "Xiaomi Redmi Note 11",
          memory: "512GB",
          Img: xiaomi,
          url: "/mobile/xiaomi/11proplus",
          price: "1000 $",
          color1: "gray",
          color2: "white",
          color3: "red",
          id: uuidv4(),
        },
      ],
    },
  ];
};
